site_name: Docker
site_author: Pedro Joya Máñez
site_description: Apuntes sobre Docker
site_url: http://informaticasaladillo.es/docker_site/
nav:
    - Inicio: index.md
    - Procesos e Hilos:
      - 1 - Program. concurrente:
        - 1.1 - Programa vs. Proceso: tema1-1.md
        - 1.2 - Computación concurrente: tema1-2.md
        - 1.3 - Procesos en el sistema operativo: tema1-3.md
        - 1.4 - Técnicas de programación concurrente: tema1-4.md
        - 1.5 - Orden de ejecución: tema1-5.md
        - 1.6 - Sincronización: tema1-6.md
        - 1.7 - Comunicación: tema1-7.md
        - 1.8 - Propiedades de corrección: tema1-8.md
      - 2 - Gestión de procesos:
        - 2.1 - Runtime: tema2-1.md
        - 2.2 - ProcessBuilder: tema2-2.md
        - 2.3 - Flujos de comunicación: tema2-3.md
        - 2.4 - Finalización: tema2-4.md
        - 2.5 - ProcessHandle: tema2-5.md
        - 2.6 - Alternativas de comunicación: tema2-6.md
      - 3 - Gestión de hilos: 
        - 3.1 - Introducción: tema3-1.md
        - 3.2 - Thread: tema3-2.md
        - 3.3 - Runnable: tema3-3.md
        - 3.4 - Prioridad: tema3-4.md
        - 3.5 - Interrumpir: tema3-5.md
        - 3.6 - Dormir: tema3-6.md
        - 3.7 - Esperar la finalización: tema3-7.md
        - 3.8 - Daemons: tema3-8.md
        - 3.9 - UncaughtExceptionHandler: tema3-9.md
        - 3.10 - ThreadGroup: tema3-10.md
        - 3.11 - ThreadFactory: tema3-11.md
        - 3.12 - ThreadLocal: tema3-12.md
      - 4 - Cerrojos: 
        - 4.1 - Introducción a los sincronizadores: tema4-1.md
        - 4.2 - Volatile: tema4-2.md
        - 4.3 - Cerrojo intrínseco: tema4-3.md
        - 4.4 - Lock striping: tema4-4.md
        - 4.5 - Busy waiting: tema4-5.md
        - 4.6 - Wait notify: tema4-6.md
        - 4.7 - Lock: tema4-7.md
        - 4.8 - Condition: tema4-8.md
        - 4.9 - ReentrantReadWriteLock: tema4-9.md
        - 4.10 - StampedLock: tema4-10.md
        - 4.11 - Semaphore: tema4-11.md
      - 5 - Barreras: 
        - 5.1 - Barreras de sincronización: tema5-1.md
        - 5.2 - CountDownLatch: tema5-2.md
        - 5.3 - CyclicBarrier: tema5-3.md
        - 5.4 - Phaser: tema5-4.md
        - 5.5 - Exchanger: tema5-5.md
      - 6 - Variables atómicas:
        - 6.1 - Paquete atomic: tema6-1.md
        - 6.2 - Variables atómicas: tema6-2.md
        - 6.3 - Acumuladores atómicos: tema6-3.md
        - 6.4 - VarHandle: tema6-4.md
      - 7 - Colecciones thread-safe:
        - 7.1 - Tipos de colecciones thread-safe: tema7-1.md
        - 7.2 - Unmodifiable collections: tema7-2.md
        - 7.3 - Copy on write collections: tema7-3.md
        - 7.4 - Inmutable collections: tema7-4.md
        - 7.5 - Synchronized collections: tema7-5.md
        - 7.6 - Concurrent-aware collections: tema7-6.md
        - 7.7 - Concurrent-aware collections que usan cerrojos: tema7-7.md
        - 7.8 - Lock-free concurrent-aware collections: tema7-8.md
      - 8 - Executor framework: 
        - 8.1 - Introducción al executor framework: tema8-1.md
        - 8.2 - Executor: tema8-2.md
        - 8.3 - ThreadPoolExecutor: tema8-3.md
        - 8.4 - Terminación de un ejecutor: tema8-4.md
        - 8.5 - CachedThreadPool: tema8-5.md
        - 8.6 - FixedThreadPool: tema8-6.md
        - 8.7 - Callable: tema8-7.md
        - 8.8 - Future: tema8-8.md
        - 8.9 - Métodos de envío de tareas en la interfaz ExecutorService: tema8-9.md
        - 8.10 - invokeAll(): tema8-10.md
        - 8.11 - invokeAny(): tema8-11.md
        - 8.12 - ThreadFactory: tema8-12.md
        - 8.13 - RejectedExecutionHandler: tema8-13.md
        - 8.14 - ScheduledThreadPoolExecutor: tema8-14.md
        - 8.15 - Planificación del inicio de ejecución de una tarea: tema8-15.md
        - 8.16 - Ejecutar una tarea de manera periódica: tema8-16.md
        - 8.17 - Cancelación de tareas y terminación del ScheduledThreadPoolExecutor: tema8-17.md
        - 8.18 - ExecutorCompletionService: tema8-18.md
        - 8.19 - FutureTask: tema8-19.md
      - 9 - Fork-Join framework: 
        - 9.1 - Introducción al Fork-Join framework: tema9-1.md
        - 9.2 - ForkJoinPool: tema9-2.md
        - 9.3 - ForkJoinTask: tema9-3.md
        - 9.4 - Algoritmo de robo de trabajo: tema9-4.md
        - 9.5 - RecursiveAction: tema9-5.md
        - 9.6 - RecursiveTask: tema9-6.md
        - 9.7 - CountedCompleter: tema9-7.md
        - 9.8 - Common Fork-Join pool: tema9-8.md
      - 10 - CompletableFuture: 
        - 10.1 - Introducción a CompletableFuture: tema10-1.md
        - 10.2 - Nomenclatura de los métodos: tema10-2.md
        - 10.3 - Métodos factoría: tema10-3.md
        - 10.4 - Obtención del valor: tema10-4.md
        - 10.5 - Ejecutar un runnable asíncronamente: tema10-5.md
        - 10.6 - Consumir el resultado asíncronamente: tema10-6.md
        - 10.7 - Transformar el resultado asíncronamente: tema10-7.md
        - 10.8 - Gestión de excepciones: tema10-8.md
        - 10.9 - Completado explícito: tema10-9.md
        - 10.10 - Trabajo con más de dos CompletableFuture: tema10-10.md
    - Networking:
      - 11 - Sockets: 
        - 11.1 - Arquitectura Cliente Servidor: tema11-1.md
        - 11.2 - TCP/IP: tema11-2.md
        - 11.3 - InetAddress: tema11-3.md
        - 11.4 - Concepto de socket: tema11-4.md
        - 11.5 - Sockets orientados a conexión: tema11-5.md
        - 11.6 - Sockets no orientados a conexión: tema11-6.md
      - 12 - HTTP: 
        - 12.1 - URI: tema12-1.md
        - 12.2 - URL: tema12-2.md
        - 12.3 - URLEncoder y URLDecoder: tema12-3.md
        - 12.4 - UrlConnection: tema12-4.md
        - 12.5 - Protocolo HTTP: tema12-5.md
        - 12.6 - Arquitectura REST: tema12-6.md
        - 12.7 - HttpURLConnection: tema12-7.md
        - 12.8 - OkHttp: tema12-8.md
        - 12.9 - HttpClient: tema12-9.md
        - 12.10 - Retrofit: tema12-10.md
    - Corutinas:
      - 13 - Kotlin coroutines:
        - 13.1 - Técnicas de programación asíncrona: tema13-1.md
        - 13.2 - Nuestra primera corutina: tema13-2.md
        - 13.3 - Jobs y funciones suspendibles: tema13-3.md
        - 13.4 - Concurrencia estructurada: tema13-4.md
        - 13.5 - Contextos y dispatchers: tema13-5.md
        - 13.6 - Ámbitos y subámbitos: tema13-6.md
        - 13.7 - Cancelación: tema13-7.md
        - 13.8 - async: tema13-8.md
        - 13.9 - Gestión de excepciones: tema13-9.md
    - Programación segura:
      - 14 - Criptografía:
        - 14.1 - Objetivos de seguridad: tema14-1.md
        - 14.2 - Definición de criptografía: tema14-2.md
        - 14.3 - Principios criptográficos: tema14-3.md
        - 14.4 - Clasificación de algoritmos criptográficos: tema14-4.md
        - 14.5 - JCA y JCE: tema14-5.md
        - 14.6 - Proveedores y motores criptográficos: tema14-6.md
        - 14.7 - Claves criptográficas: tema14-7.md
        - 14.8 - Funciones hash: tema14-8.md
        - 14.9 - Algoritmos de criptografía simétrica: tema14-9.md
        - 14.10 - Algoritmos de criptografía asimétrica: tema14-10.md
        - 14.11 - Firma digital: tema14-11.md
        - 14.12 - Certificado digital: tema14-12.md
        - 14.13 - Almacén de claves: tema14-13.md
    - Android:
      - 15 - Multihilo en Android:
        - 15.1 - El hilo principal en Android: tema15-1.md
        - 15.2 - Paso de mensajes al hilo principal: tema15-2.md
        - 15.3 - Handler y Looper: tema15-3.md
theme:
  name: material
  language: es
  palette:
    primary: deep purple
    accent: indigo
  logo: 'assets/logo.gif'
  favicon: 'assets/favicon.png'
  features:
    - navigation.sections
    - toc.integrate
    - navigation.tabs
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.tabbed 
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - 'stylesheets/extra.css'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/pedrojoya'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/pedrojoyamanez'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/playlist?list=PLK6RrRW5qdCO9u2LLu22KqHikjEo-Tssc'
plugins:
  - search
  - git-revision-date-localized
  - autolinks
  - awesome-pages
