site_name: Docker
site_author: Pedro Joya Máñez
site_description: Apuntes sobre Docker
site_url: http://informaticasaladillo.es/docker_site/
nav:
    - Inicio: index.md
    - 1 - Introducción a Docker para desarrolladores:
      - 1.1 - ¿Qué es Docker?: tema1-1.md
      - 1.2 - Instalación de Docker: tema1-2.md
      - 1.3 - Nuestro primer contenedor: tema1-3.md
      - 1.4 - ¿Qué es Docker Hub?: tema1-4.md
      - 1.5.- Uso de Docker para la docencia: tema1-5.md
      - 1.6.- Tareas del tema: tema1-6.md
    - 2 - Ejecución y gestión de contenedores:
      - 2.1.- Ejecución de contenedores: tema2-1.md
      - 2.2.- Listar los contenedores existentes: tema2-2.md
      - 2.3.- Asignando nombre a los contenedores: tema2-3.md
      - 2.4.- Arranque interactivo de un contenedor: tema2-4.md
      - 2.5.- Ejecución de servicios. Puertos y variables de entorno: tema2-5.md
      - 2.6.- Ejecución de órdenes en los contenedores: tema2-6.md
      - 2.7.- Copia de archivos entre el equipo local y el contenedor: tema2-7.md
      - 2.8.- Obtener información detallada de un contenedor: tema2-8.md
      - 2.9.- Mostrar logs de un contenedor: tema2-9.md
      - 2.10.- Parada, reinicio y reseteo de un contenedor: tema2-10.md
      - 2.11.- Vídeo resumen del tema: tema2-11.md
      - 2.12.- Tareas del tema: tema2-12.md
    - 3 - Gestión de imágenes:
      - 3.1.- Descarga de imágenes: tema3-1.md
      - 3.2.- Listado de imágenes: tema3-2.md
      - 3.3.- Obtener información de las imágenes: tema3-3.md
      - 3.4.- Borrado de imágenes: tema3-4.md
      - 3.5.- Otras órdenes relacionadas con las imágenes: tema3-5.md
      - 3.6.- Vídeo resumen del tema: tema3-6.md
      - 3.7.- Tareas del tema: tema3-7.md
    - 4.- Persistencia en docker:
      - 4.1.- Persistencia en los contenedores con volúmenes y bind mounts: tema4-1.md
      - 4.2.- Gestión de volúmenes: tema4-2.md
      - 4.3.- Asociando almacenamiento a los contenedores: tema4-3.md
      - 4.4.- Herramientas Docker para IDEs: tema4-4.md
      - 4.5.- Usos principales de volúmenes y bind mounts: tema4-5.md
      - 4.6.- Depurando aplicaciones con bind mounts: tema4-6.md
      - 4.7.- Tareas del tema: tema4-7.md
    - 5.- Redes en docker:
      - 5.1.- Tipos de redes en Docker: tema5-1.md
      - 5.2.- Obtener información sobre las redes: tema5-2.md
      - 5.3.- Gestión de redes docker: tema5-3.md
      - 5.4.- Asociando redes a contenedores: tema5-4.md
      - 5.5.- iptables en contenedores: tema5-5.md
      - 5.6.- Vídeo resumen del tema: tema5-6.md
      - 5.7.- Tareas del tema: tema5-7.md
    - 6.- Creación de imágenes:
      - 6.1.- Imágenes personalizadas: tema6-1.md
      - 6.2.- Crear una imagen a partir de un contenedor: tema6-2.md
      - 6.3.- Crear una imagen a partir de un fichero Dockerfile: tema6-3.md
      - 6.4.- Definición de un fichero Dockerfile: tema6-4.md
      - 6.5.- Fichero .dockerignore: tema6-5.md
      - 6.6.- Conectando GitHub a DockerHub: tema6-6.md
      - 6.7.- Tareas del tema: tema6-7.md
    - 7.- Aplicaciones multicapa con docker-compose:
      - 7.1.- docker-compose: tema7-1.md
      - 7.2.- El archivo docker-compose.yml: tema7-2.md
      - 7.3.- La orden docker-compose: tema7-3.md
      - 7.4.- Aplicaciones en la docencia: tema7-4.md
      - 7.5.- Publicación de archivos docker-compose en DockerHub: tema7-5.md
      - 7.6.- Tareas del tema: tema7-6.md
    - 8.- Asegurando contenedores:
      - 8.1.- Seguridad en las imágenes: tema8-1.md
      - 8.2.- Seguridad en el proceso de build: tema8-2.md
      - 8.3.- Seguridad al arrancar los contenedores: tema8-3.md
      - 8.4.- Vídeo resumen del tema: tema8-4.md
      - 8.5.- Tareas del tema: tema8-5.md
    - 9.- Jenkins y Docker:
      - 9.1.- Conceptos básicos de integración y despliegue continuo: tema9-1.md
      - 9.2.- Ejemplo práctico de Jenkins y Docker: tema9-2.md
      - 9.3.- Tareas del tema: tema9-3.md 

theme:
  name: material
  language: es
  palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: deep purple
        accent: indigo
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: deep purple
        accent: indigo
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode  
  logo: 'assets/logo.gif'
  favicon: 'assets/favicon.png'
  features:
    - toc.integrate
    - navigation.top
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.tabbed 
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - 'stylesheets/extra.css'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/pedrojoya'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/pedrojoyamanez'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/playlist?list=PLK6RrRW5qdCO9u2LLu22KqHikjEo-Tssc'
plugins:
  - search
  - git-revision-date-localized
  - autolinks
  - awesome-pages
